name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule: [cron: "*/15 * * * *"]

jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and simulate
        run : |
          sudo apt-get update
          sudo apt-get install -y iverilog verilator
          # Local install Cocotb and set PATH env
          pip3 install cocotb
          export PATH="$HOME/.local/bin:$PATH"
          TEST_LOG="test.log"
          CI_ENV="true" ./run.sh 2>&1 | tee $TEST_LOG
          if [ `grep -c FAILURE $TEST_LOG | cat` -ne 0 ]; then
            grep FAILURE $TEST_LOG
            echo "there is assertion failure uncaught!"
            exit 1
          fi
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
