name: CI
on:
  pull_request:
    branches: [master]
  schedule: [cron: "12 */24 * * *"]

jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run : |
          ./run.sh

