name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule: [cron: "12 */24 * * *"]

jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and simulate
        run : |
          sudo apt-get update
          sudo apt-get install -y iverilog verilator
          # Local install Cocotb and set PATH env
          pip3 install cocotb
          export PATH="$HOME/.local/bin:$PATH"
          ./run.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
